#########################################################
#                                                       #
#             Nightly Hass.io Snapshot                  #
#                                                       #
#########################################################

  - alias: Hassio Snapshot
    initial_state: 'on'
    trigger:
    - platform: time
      at: '03:00:00'
    condition: []
    action:
    - service: hassio.snapshot_full
      data_template:
        name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
    - service: notify.ios_adams_iphone
      data_template:
        title: New Hass.io Backup
        message: Created is named "Automated Backup {{ now().strftime('%Y-%m-%d') }}"

#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################