homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 39.8802
  longitude: -104.7920
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5190
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: MST
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
  
#App integrations  
ios:

# Cloud
cloud:

# MQTT
mqtt:
 broker: localhost
 discovery: true
 discovery_prefix: smartthings

# Unifi Device tracker
device_tracker:
  - platform: unifi
    host: unifi.cadcom.us
    username: brendan
    password: !secret normal_pw
    ssl: false

tuya:
  username: brendan.galloway@gmail.com
  password: !secret normal_pw
  country_code: 1

# Sensors
sensor: !include_dir_merge_list sensors/
binary_sensor:
  - platform: workday
    country: US


#Lights
light: !include_dir_merge_list lights/

#Locks
lock:
  - platform: mqtt
    name: Front Door
    state_topic: "smartthings/Front Door/lock/state"
    command_topic: "smartthings/Front Door/lock/cmd"
    payload_lock: "locked"
    payload_unlock: "unlocked"
    optimistic: false
    qos: 1
    retain: true

#Media Players
media_player:
  - platform: firetv
    name: Bedroom Fire TV
    host: 10.222.73.34


panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
